config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :new, :create, :show, :edit, :update, :delete] do
    resources :comments, only: [:create]
  end
  
  delete 'product' => 'products#destroy'

  resources :charges
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  #Devise gem with facebook omniauth, hits users controller with callbacks redirect
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-primary" %>

<%= link_to "Checkout", new_charge_path, class: "btn btn-info" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>GKT</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- FAVICON START -->
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
<!-- FAVICON END -->
    </head>

<!-- page-wrapper START -->
<div class="page-wrapper">

    <div class="container">
        <header>
            <div class="container">
                <%= render 'partials/navbar' %>
            </div>
            <div class="container">
              <div class="notice_bar">
                <%= render 'partials/notice' %>
              </div>
            </div>
        </header>
    </div>

    <body>

        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h1><%= link_to "GKT", root_path %></h1>
                </div>
                <div class="col-xs-6 text-right">
                    <h1 class="cart-text">
                        <%= render 'layouts/cart_text' %>
                    </h1>
                </div>
                <div class="container">
                    <%= yield %>
                </div>

            </div>
        </div>

<!-- Test Display Total amount -->
        <div class="container">
          <%= current_order.subtotal %>
        </div>
<!-- Test Display Total amount -->


        <footer>
            <div class="container">
                DX STUDIOS
            </div>
        </footer>

    </body>
</div>
<!-- page-wrapper END -->
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <%= yield %>
    </body>
</html>